spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
