# =========================================================
# SPRING BOOT PROPERTIES - EXERCISE 9
# =========================================================
server.port=8080

# H2 Database URL configurations
spring.datasource.url=jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate DDL generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

